apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patchesStrategicMerge:
  - deployment.yaml
  - service.yaml
namespace: instavote
images:
  - name: schoolofdevops/vote
    newTag: v4
replicas:
  - name: vote
    count: 4
commonLabels:
  project: instavote
  env: vote-staging
commonAnnotations:
  supported-by: "src@example.com"
